env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
rules: {
  'linebreak-style': 0,
  'indent': 0,
  'no-param-reassign': 0,
  'no-console': 0
}
